# Generated by Django 5.1.4 on 2024-12-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('normal', 'Normal'), ('admin', 'Admin')], default='normal', max_length=10),
        ),
    ]
