# Generated by Django 5.1.4 on 2024-12-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('encrypted_data', models.BinaryField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
