# Generated by Django 5.1.4 on 2024-12-28 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_alter_user_role'),
        ('files', '0003_alter_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filetype',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.CreateModel(
            name='FileAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_time', models.DateTimeField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_access', to='files.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_access', to='custom_auth.user')),
            ],
            options={
                'unique_together': {('user', 'file')},
            },
        ),
    ]
