# Generated by Django 5.1.4 on 2024-12-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_filetype_fileaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaccess',
            name='expiration_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
