export const FILE_ACCESS_LIST = "FILE_ACCESS_LIST";
export const FILE_ACCESS_LIST_SUCCESS = "FILE_ACCESS_LIST_SUCCESS";
export const FILE_ACCESS_LIST_FAILURE = "FILE_ACCESS_LIST_FAILURE";

export const DELETE_FILE_ACCESS = "DELETE_FILE_ACCESS";
export const DELETE_FILE_ACCESS_SUCCESS = "DELETE_FILE_ACCESS_SUCCESS";
export const DELETE_FILE_ACCESS_FAIL = "DELETE_FILE_ACCESS_FAIL";

export const GIVE_FILE_ACCESS = "GIVE_FILE_ACCESS";
export const GIVE_FILE_ACCESS_SUCCESS = "GIVE_FILE_ACCESS_SUCCESS";
export const GIVE_FILE_ACCESS_FAIL = "GIVE_FILE_ACCESS_FAIL";

export const EDIT_FILE_ACCESS = "EDIT_FILE_ACCESS";
export const EDIT_FILE_ACCESS_SUCCESS = "EDIT_FILE_ACCESS_SUCCESS";
export const EDIT_FILE_ACCESS_FAIL = "EDIT_FILE_ACCESS_FAIL";